const customerOrders = [
    {
      id: 1,
      name: "Washington Sundar",
      orderDate: "12 Aug 2022 - 12:25 am",
      orderType: "Home Delivery",
      tractingId: "9348fjr73",
      orderTotal: "25000",
      Action: "Completed",
      Status: "Completed",
    },
    {
      id: 2,
      name: "Sanju Samson",
      orderDate: "12 Sep 2022 - 12:25 am",
      orderType: "Home Delivery",
      tractingId: "9348fjr73",
      orderTotal: "30000",
      Action: "In-Progress",
      Status: "In-Progress",
    },
    {
      id: 3,
      name: "Rinku Singh",
      orderDate: "12 Jun 2022 - 12:25 am",
      orderType: "Pick Up",
      tractingId: "9348fjr73",
      orderTotal: "45000",
      Action: "Pending",
      Status: "Pending",
    },
    {
      id: 4,
      name: "Riyan Parag",
      orderDate: "12 Jul 2022 - 12:25 am",
      orderType: "Pick Up",
      tractingId: "9348fjr73",
      orderTotal: "26000",
      Action: "Completed",
      Status: "Completed",
    },
    {
      id: 5,
      name: "Tilak Varma",
      orderDate: "12 Nov 2022 - 12:25 am",
      orderType: "Pick Up",
      tractingId: "9348fjr73",
      orderTotal: "27000",
      Action: "In-Progress",
      Status: "In-Progress",
    },
    {
      id: 6,
      name: "Steve Smith",
      orderDate: "12 Jan 2022 - 12:25 am",
      orderType: "Home Delivery",
      tractingId: "9348fjr73",
      orderTotal: "39000",
      Action: "Pending",
      Status: "Pending",
    },
    {
      id: 7,
      name: "Ruturaj Gaikwad",
      orderDate: "12 May 2022 - 12:25 am",
      orderType: "Pick Up",
      tractingId: "9348fjr73",
      orderTotal: "46000",
      Action: "Completed",
      Status: "Completed",
    },
    {
      id: 8,
      name: "Sai Sudarshan",
      orderDate: "12 Mar 2022 - 12:25 am",
      orderType: "Pick Up",
      tractingId: "9348fjr73",
      orderTotal: "65000",
      Action: "In-Progress",
      Status: "In-Progress",
    },
    {
      id: 9,
      name: "Abhishek Sharma",
      orderDate: "12 Nov 2022 - 12:25 am",
      orderType: "Home Delivery",
      tractingId: "9348fjr73",
      orderTotal: "72000",
      Action: "Pending",
      Status: "Pending",
    },
    {
      id: 10,
      name: "Harshit Rana",
      orderDate: "12 Oct 2022 - 12:25 am",
      orderType: "Pick Up",
      tractingId: "9348fjr73",
      orderTotal: "39000",
      Action: "Completed",
      Status: "Completed",
    },
  ];
  
  export default customerOrders;
  